USE [Job_No_99]
GO

/****** Object:  Table [dbo].[RT101_LOGSHEET_REV02_HEADER]    Script Date: 2023-10-27 13:24:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[R_101_HEADER_LOGSHEET](
	[REACTOR_NAME] [nvarchar](50) NULL,
	[PRODUCT_CODE] [nvarchar](50) NULL,
	[BATCH_NO] [nvarchar](50) NULL,
	[BATCH_SIZE] [nvarchar](50) NULL,
	[TOTAL_BATCH_TIME] [real] NULL,
	[EMULSION_START_TIME] [datetime] NULL,
	[EMULSION_END_TIME] [datetime] NULL,
	[REACTOR_INITIAL_WEIGHT] [real] NULL,
	[REACTOR_FINAL_WEIGHT] [real] NULL,
	[REACTOR_START_TIME] [datetime] NULL,
	[REACTOR_END_TIME] [datetime] NULL,
	[WATER_PHASE_TIME] [real] NULL,
	[SEED_TIME] [real] NULL,
	[SEED_TEMP] [real] NULL,
	[SEED_QTY] [real] NULL,
	[FEEDING_TIME] [real] NULL,
	[POST_ADDITION_TIME] [real] NULL,
	[QC_TIME] [real] NULL,
	[DOWNING_TIME] [real] NULL,
	[SBP_SEED_TEMP_RANGE] [real] NULL,
	[SBP_SEED_QTY_KG] [real] NULL,
	[SBP_FEEDING_TIME_HR] [real] NULL,
	[SBP_REACTION_TEMP] [real] NULL,
	[SBP_AFTER_FEEDING_HOLD_TIME] [real] NULL,
	[SBP_NH3_ADD_TEMP] [real] NULL,
	[SBP_TBHP_ADD_TEMP] [real] NULL,
	[SBP_DECOLITE_ADD_TEMP] [real] NULL,
	[SBP_STD_BATCH_HR] [real] NULL,
	[ETTC_CHECK1] [nvarchar](50) NULL,
	[ETTC_CHECK2] [nvarchar](50) NULL,
	[ETTC_CHECK3] [nvarchar](50) NULL,
	[ETTC_CHECK4] [nvarchar](50) NULL,
	[ETTC_CHECK5] [nvarchar](50) NULL,
	[RTTC_CHECK1] [nvarchar](50) NULL,
	[RTTC_CHECK2] [nvarchar](50) NULL,
	[RTTC_CHECK3] [nvarchar](50) NULL,
	[RTTC_CHECK4] [nvarchar](50) NULL,
	[RTTC_CHECK5] [nvarchar](50) NULL,
	[RTTC_CHECK6] [nvarchar](50) NULL,
	[RTTC_CHECK7] [nvarchar](50) NULL,
	[RTTC_CHECK8] [nvarchar](50) NULL,
	[RTTC_CHECK9] [nvarchar](50) NULL,
	[RTTC_CHECK10] [nvarchar](50) NULL,
	[RTTC_CHECK11] [nvarchar](50) NULL,
	[PD_NW_2_80T] [real] NULL,
	[PD_NW_8_2NM] [real] NULL,
	[PD_NW_8_5NM] [real] NULL,
	[PD_NW_9_40NM] [real] NULL,
	[PD_NW_9_80NM] [real] NULL,
	[PD_NW_IBC] [real] NULL,
	[PD_NW_FLEXI] [real] NULL,
	[PD_NW_OTHER] [real] NULL,
	[PD_NW_LOOSE] [real] NULL,
	[PD_NOS_2_80T] [real] NULL,
	[PD_NOS_8_2NM] [real] NULL,
	[PD_NOS_8_5NM] [real] NULL,
	[PD_NOS_9_40NM] [real] NULL,
	[PD_NOS_9_80NM] [real] NULL,
	[PD_NOS_IBC] [real] NULL,
	[PD_NOS_FLEXI] [real] NULL,
	[PD_NOS_OTHER] [real] NULL,
	[PD_NOS_LOOSE] [real] NULL,
	[PD_TOTAL_WEIGHT] [real] NULL,
	[TR_ET_SPEC_PH] [real] NULL,
	[TR_ET_SPEC_VISCOSITY] [real] NULL,
	[TR_ET_SPEC_STABILITY] [nvarchar](50) NULL,
	[TR_WP_PH_OF_WP] [real] NULL,
	[TR_WP_WP_STATUS] [real] NULL,
	[TR_WP_PPS_TEMP] [nvarchar](50) NULL,
	[TR_STD_SOLID] [real] NULL,
	[TR_STD_VISCOSITY] [real] NULL,
	[TR_STD_APPEARANCE] [real] NULL,
	[TR_STD_PH] [real] NULL,
	[TR_STD_SPECIFIC_GRAVITY] [real] NULL,
	[TR_ACT_SOLID] [real] NULL,
	[TR_ACT_VISCOSITY] [real] NULL,
	[TR_ACT_APPEARANCE] [real] NULL,
	[TR_ACT_PH] [real] NULL,
	[TR_ACT_SPECIFIC_GRAVITY] [real] NULL,
	[TR_OTHER_IF_ANY] [nvarchar](50) NULL,
	[SPARE1] [nvarchar](50) NULL,
	[SPARE2] [nvarchar](50) NULL,
	[SPARE3] [nvarchar](50) NULL,
	[SPARE4] [nvarchar](50) NULL,
	[SPARE5] [nvarchar](50) NULL,
	[SPARE6] [nvarchar](50) NULL,
	[SPARE7] [nvarchar](50) NULL
) ON [PRIMARY]
GO


