package com.example.demo.entity;

import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "R_101_BATCH_REPORT")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BatchReport {
	@Id
	private String batchNo;
	private LocalDate dateTime;
	private String reactorName;
	private String productName;
	private String batchSize;
	private BigDecimal rtHdmwSp;
	private BigDecimal rtHdmwPv;
	private BigDecimal rtDmwSp;
	private BigDecimal rtDmwPv;
	private String rtHdmwRmbn;
	private String rtDmwRmbn;
	private String iniMaterial1;
	private String iniMaterial2;
	private String iniMaterial3;
	private String iniMaterial4;
	private String iniMaterial5;
	private String iniMaterial6;
	private String iniMaterial7;
	private String iniMaterial8;
	private String iniMaterial9;
	private String iniMaterial10;
	private BigDecimal iniSpI1;
	private BigDecimal iniSpI2;
	private BigDecimal iniSpI3;
	private BigDecimal iniSpI4;
	private BigDecimal iniSpI5;
	private BigDecimal iniSpI6;
	private BigDecimal iniSpI7;
	private BigDecimal iniSpI8;
	private BigDecimal iniSpI9;
	private BigDecimal iniSpI10;
	private BigDecimal iniPvI1;
	private BigDecimal iniPvI2;
	private BigDecimal iniPvI3;
	private BigDecimal iniPvI4;
	private BigDecimal iniPvI5;
	private BigDecimal iniPvI6;
	private BigDecimal iniPvI7;
	private BigDecimal iniPvI8;
	private BigDecimal iniPvI9;
	private BigDecimal iniPvI10;
	private String iniRmbnI1;
	private String iniRmbnI2;
	private String iniRmbnI3;
	private String iniRmbnI4;
	private String iniRmbnI5;
	private String iniRmbnI6;
	private String iniRmbnI7;
	private String iniRmbnI8;
	private String iniRmbnI9;
	private String iniRmbnI10;
	private String etMaterial1;
	private String etMaterial2;
	private String etMaterial3;
	private String etMaterial4;
	private String etMaterial5;
	private String etMaterial6;
	private String etMaterial7;
	private String etMaterial8;
	private String etMaterial9;
	private String etMaterial10;
	private String etMaterial11;
	private String etMaterial12;
	private BigDecimal etSpI1;
	private BigDecimal etSpI2;
	private BigDecimal etSpI3;
	private BigDecimal etSpI4;
	private BigDecimal etSpI5;
	private BigDecimal etSpI6;
	private BigDecimal etSpI7;
	private BigDecimal etSpI8;
	private BigDecimal etSpI9;
	private BigDecimal etSpI10;
	private BigDecimal etSpI11;
	private BigDecimal etSpI12;
	private BigDecimal etPvI1;
	private BigDecimal etPvI2;
	private BigDecimal etPvI3;
	private BigDecimal etPvI4;
	private BigDecimal etPvI5;
	private BigDecimal etPvI6;
	private BigDecimal etPvI7;
	private BigDecimal etPvI8;
	private BigDecimal etPvI9;
	private BigDecimal etPvI10;
	private BigDecimal etPvI11;
	private BigDecimal etPvI12;
	private String etRmbnI1;
	private String etRmbnI2;
	private String etRmbnI3;
	private String etRmbnI4;
	private String etRmbnI5;
	private String etRmbnI6;
	private String etRmbnI7;
	private String etRmbnI8;
	private String etRmbnI9;
	private String etRmbnI10;
	private String etRmbnI11;
	private String etRmbnI12;
	private BigDecimal pps1HdmwSp;
	private BigDecimal pps1DmwSp;
	private BigDecimal pps1PpsSp;
	private BigDecimal pps1HdmwPv;
	private BigDecimal pps1DmwPv;
	private BigDecimal pps1PpsPv;
	private String pps1HdmwRmbn;
	private String pps1DmwRmbn;
	private BigDecimal pps1PpsRmbn;
	private BigDecimal pps2DmwPpsSp;
	private BigDecimal pps2DmwPpsPv;
	private String pps2DmwPpsRmbn;
	private BigDecimal ppsAfterFeedingHdmwSp;
	private BigDecimal ppsAfterFeedingDmwSp;
	private BigDecimal ppsAfterFeedingPpsSp;
	private BigDecimal ppsAfterFeedingHdmwPv;
	private BigDecimal ppsAfterFeedingDmwPv;
	private BigDecimal ppsAfterFeedingPpsPv;
	private String ppsAfterFeedingHdmwRmbn;
	private String ppsAfterFeedingDmwRmbn;
	private String ppsAfterFeedingPpsRmbn;
	private BigDecimal cntPpsDmwSp;
	private BigDecimal cntPpsPpsSp;
	private BigDecimal cntPpsDmwPv;
	private BigDecimal cntPpsPpsPv;
	private String cntPpsDmwRmbn;
	private String cntPpsPpsRmbn;
	private String postAdMaterial1;
	private String postAdMaterial2;
	private String postAdMaterial3;
	private String postAdMaterial4;
	private String postAdMaterial5;
	private String postAdMaterial6;
	private String postAdMaterial7;
	private String postAdMaterial8;
	private String postAdMaterial9;
	private String postAdMaterial10;
	private BigDecimal postAdSpI1;
	private BigDecimal postAdSpI2;
	private BigDecimal postAdSpI3;
	private BigDecimal postAdSpI4;
	private BigDecimal postAdSpI5;
	private BigDecimal postAdSpI6;
	private BigDecimal postAdSpI7;
	private BigDecimal postAdSpI8;
	private BigDecimal postAdSpI9;
	private BigDecimal postAdSpI10;
	private BigDecimal postAdPvI1;
	private BigDecimal postAdPvI2;
	private BigDecimal postAdPvI3;
	private BigDecimal postAdPvI4;
	private BigDecimal postAdPvI5;
	private BigDecimal postAdPvI6;
	private BigDecimal postAdPvI7;
	private BigDecimal postAdPvI8;
	private BigDecimal postAdPvI9;
	private BigDecimal postAdPvI10;
	private String postAdI1Rmbn;
	private String postAdI2Rmbn;
	private String postAdI3Rmbn;
	private String postAdI4Rmbn;
	private String postAdI5Rmbn;
	private String postAdI6Rmbn;
	private String postAdI7Rmbn;
	private String postAdI8Rmbn;
	private String postAdI9Rmbn;
	private String postAdI10Rmbn;
	private BigDecimal qcDmwSp;
	private BigDecimal qcNh3Sp;
	private BigDecimal qcDmwPv;
	private BigDecimal qcNh3Pv;
	private String qcDmwRmbn;
	private String qcNh3Rmbn;
	private BigDecimal whiteWaterQty;
	private String blendingMaterial;
	private String remarks;
	private String spare1;
	private String spare2;
	private String spare3;
	private String spare4;
	private String spare5;
}
