package com.example.demo.entity;

import java.util.Date;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "R_101_BATCH_REPORT")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BatchReport {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	private Date dateTime;
	private String reactorName;
	private String productName;
	private String batchNo;
	private String batchSize;
	private Float rtHdmwSp;
	private Float rtHdmwPv;
	private Float rtDmwSp;
	private Float rtDmwPv;
	private String rtHdmwRmbn;
	private String rtDmwRmbn;
	private String iniMaterial1;
	private String iniMaterial2;
	private String iniMaterial3;
	private String iniMaterial4;
	private String iniMaterial5;
	private String iniMaterial6;
	private String iniMaterial7;
	private String iniMaterial8;
	private String iniMaterial9;
	private String iniMaterial10;
	private Float iniSpI1;
	private Float iniSpI2;
	private Float iniSpI3;
	private Float iniSpI4;
	private Float iniSpI5;
	private Float iniSpI6;
	private Float iniSpI7;
	private Float iniSpI8;
	private Float iniSpI9;
	private Float iniSpI10;
	private Float iniPvI1;
	private Float iniPvI2;
	private Float iniPvI3;
	private Float iniPvI4;
	private Float iniPvI5;
	private Float iniPvI6;
	private Float iniPvI7;
	private Float iniPvI8;
	private Float iniPvI9;
	private Float iniPvI10;
	private String iniRmbnI1;
	private String iniRmbnI2;
	private String iniRmbnI3;
	private String iniRmbnI4;
	private String iniRmbnI5;
	private String iniRmbnI6;
	private String iniRmbnI7;
	private String iniRmbnI8;
	private String iniRmbnI9;
	private String iniRmbnI10;
	private String etMaterial1;
	private String etMaterial2;
	private String etMaterial3;
	private String etMaterial4;
	private String etMaterial5;
	private String etMaterial6;
	private String etMaterial7;
	private String etMaterial8;
	private String etMaterial9;
	private String etMaterial10;
	private String etMaterial11;
	private String etMaterial12;
	private Float etSpI1;
	private Float etSpI2;
	private Float etSpI3;
	private Float etSpI4;
	private Float etSpI5;
	private Float etSpI6;
	private Float etSpI7;
	private Float etSpI8;
	private Float etSpI9;
	private Float etSpI10;
	private Float etSpI11;
	private Float etSpI12;
	private Float etPvI1;
	private Float etPvI2;
	private Float etPvI3;
	private Float etPvI4;
	private Float etPvI5;
	private Float etPvI6;
	private Float etPvI7;
	private Float etPvI8;
	private Float etPvI9;
	private Float etPvI10;
	private Float etPvI11;
	private Float etPvI12;
	private String etRmbnI1;
	private String etRmbnI2;
	private String etRmbnI3;
	private String etRmbnI4;
	private String etRmbnI5;
	private String etRmbnI6;
	private String etRmbnI7;
	private String etRmbnI8;
	private String etRmbnI9;
	private String etRmbnI10;
	private String etRmbnI11;
	private String etRmbnI12;
	private Float pps1HdmwSp;
	private Float pps1DmwSp;
	private Float pps1PpsSp;
	private Float pps1HdmwPv;
	private Float pps1DmwPv;
	private Float pps1PpsPv;
	private String pps1HdmwRmbn;
	private String pps1DmwRmbn;
	private Float pps1PpsRmbn;
	private Float pps2DmwPpsSp;
	private Float pps2DmwPpsPv;
	private String pps2DmwPpsRmbn;
	private Float ppsAfterFeedingHdmwSp;
	private Float ppsAfterFeedingDmwSp;
	private Float ppsAfterFeedingPpsSp;
	private Float ppsAfterFeedingHdmwPv;
	private Float ppsAfterFeedingDmwPv;
	private Float ppsAfterFeedingPpsPv;
	private String ppsAfterFeedingHdmwRmbn;
	private String ppsAfterFeedingDmwRmbn;
	private String ppsAfterFeedingPpsRmbn;
	private Float cntPpsDmwSp;
	private Float cntPpsPpsSp;
	private Float cntPpsDmwPv;
	private Float cntPpsPpsPv;
	private String cntPpsDmwRmbn;
	private String cntPpsPpsRmbn;
	private String postAdMaterial1;
	private String postAdMaterial2;
	private String postAdMaterial3;
	private String postAdMaterial4;
	private String postAdMaterial5;
	private String postAdMaterial6;
	private String postAdMaterial7;
	private String postAdMaterial8;
	private String postAdMaterial9;
	private String postAdMaterial10;
	private Float postAdSpI1;
	private Float postAdSpI2;
	private Float postAdSpI3;
	private Float postAdSpI4;
	private Float postAdSpI5;
	private Float postAdSpI6;
	private Float postAdSpI7;
	private Float postAdSpI8;
	private Float postAdSpI9;
	private Float postAdSpI10;
	private Float postAdPvI1;
	private Float postAdPvI2;
	private Float postAdPvI3;
	private Float postAdPvI4;
	private Float postAdPvI5;
	private Float postAdPvI6;
	private Float postAdPvI7;
	private Float postAdPvI8;
	private Float postAdPvI9;
	private Float postAdPvI10;
	private String postAdI1Rmbn;
	private String postAdI2Rmbn;
	private String postAdI3Rmbn;
	private String postAdI4Rmbn;
	private String postAdI5Rmbn;
	private String postAdI6Rmbn;
	private String postAdI7Rmbn;
	private String postAdI8Rmbn;
	private String postAdI9Rmbn;
	private String postAdI10Rmbn;
	private Float qcDmwSp;
	private Float qcNh3Sp;
	private Float qcDmwPv;
	private Float qcNh3Pv;
	private String qcDmwRmbn;
	private String qcNh3Rmbn;
	private Float whiteWaterQty;
	private String blendingMaterial;
	private String remarks;
	private String spare1;
	private String spare2;
	private String spare3;
	private String spare4;
	private String spare5;
}
